language: go

sudo: false

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go vet ./...

go:
  - "1.10.x"
  - "1.11.x"
  - tip

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
